### ISSUE TITLE
public static void convertToZip(Path validInputDir)

### ISSUE THREAD

**Issue by campellcl** [JaysGitLab/cs-5666-scatt-scattcats#31]
Write a method that takes as input a storage directory. Upon completion the method will have renamed all files ending in .sb2 to .zip. The zip files can then be extracted.

**Comment by cambelem** [comment]
Already working on this.. apparently the branch issue changed from 27 to 31? I need to fix checkstyle, but other than that, it's good to go.

**Comment by cambelem** [comment]
Actually isn't this issue12?

**Comment by campellcl** [comment]
It would have been better to write a whole new 'Epic' for issue 12 and not have had it been a card at all. It is way too vague. It takes multiple methods to accomplish issue 12. This method is just one method from issue 12. My bad!
